# Generated by Django 6.0.4 on 2026-04-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_short_dscription_blog_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
    ]
